version: '2'
services:  
      
  jupyter_scipy:
    image: jupyter/scipy-notebook:2c80cf3537ca
    volumes:
      - "$PWD":/jupyter-work:/work
        # Enable you to access potainers web interface from your host machine
        # using http://localhost:8888
    ports:
      - "8888:8888"
	  
  jupyter_all_spark:
    image: jupyter/all-spark-notebook
    volumes:
      - "$PWD":/jupyter-work:/work
        # Enable you to access potainers web interface from your host machine
        # using http://localhost:8888
    ports:
      - "8889:8888"
